name: github-checks
on:
  pull_request:
    branches:
      - master

jobs:
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - id: files
       uses: jitterbit/get-changed-files@v1
       continue-on-error: true
     - uses: dbelyaev/action-checkstyle@master
       with:
         reporter: github-pr-review
         checkstyle_config: codestyle/naver-checkstyle-rules.xml
		 properties_file: codestyle/naver-checkstyle-suppressions.xml
